server:
  port: 8500

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  server:
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8500/eureka/}